services:
  livekit:
    image: livekit/livekit-server:latest
    command: --dev --bind 0.0.0.0
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    volumes:
      - livekit-data:/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data"]
    user: "1000:1000"
    volumes:
      - ./data/dynamodb:/data

  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  livekit-data:
  mongo-data: